name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

permissions:
  contents: read  # Gives permission to read/write to the repo
  packages: read  # Gives permission to read/write nuget packages
  
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.DA_SECRET }}
        submodules: true
